<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'News Item ID' => '',
    'Url' => '',
    'Auhtor' => 'Autor',
    'Create date' => 'Data utworzenia',
    'Enable sections ' => 'Włącz sekcje',
    'Gallery' => 'Galeria',
    'General' => 'Główne',
    'ID' => 'ID',
    'Image' => 'Obraz',
    'Image mobile' => 'Obraz mobile',
    'Language' => 'Język',
    'Languages' => 'Języki',
    'Link' => 'Link',
    'Link should be unique.' => 'Link powinien być unikalny',
    'Link title' => 'Tytuł linku',
    'Meta tags' => 'Meta tagi',
    'New tab' => 'Nowa zakładka',
    'News' => 'Aktualności',
    'News ID' => 'ID aktualności',
    'News list' => 'Lista aktualności',
    'News on page' => 'Liczba aktualności na stronie',
    'Overview page' => 'Strona przeglądu aktualności',
    'Page' => 'Strona',
    'Publish' => 'Publikuj',
    'Save entry to see additional fields' => 'Zapisz zmiany by zobaczyć dodatkowe pola',
    'Sections' => 'Sekcje',
    'Settings' => 'Ustawienia',
    'Sort' => 'Kolejność',
    'Template' => 'Szablon',
    'Text' => 'Tekst',
    'Text and image' => 'Tekst i obraz',
    'Title' => 'Tytuł',
    'Type' => 'Typ',
];
